export enum EEnvKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    API_PREFIX = 'API_PREFIX',
    SWAGGER_PATH = 'SWAGGER_PATH',

    JWT_ACCESS_SECRET_KEY = 'JWT_ACCESS_SECRET_KEY',
    JWT_ACCESS_EXPIRE_TIME = 'JWT_ACCESS_EXPIRE_TIME',
    JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY',
    JWT_REFRESH_EXPIRE_TIME = 'JWT_REFRESH_EXPIRE_TIME',

    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_DATABASE = 'DB_DATABASE',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',

    WEB3_PROVIDER = 'WEB3_PROVIDER',
    MESSAGE_FOR_SIGN = 'MESSAGE_FOR_SIGN',
}
