CREATE TABLE IF NOT EXISTS "users" (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  name CHARACTER VARYING NOT NULL
);
SELECT diesel_manage_updated_at('users');
